required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen"
]

[[override]]
  name = "github.com/gardener/gardener"
  revision = "33b9c9e2343bd7aef704f1d09b030e814e706cd6"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "0.1.9"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.2"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.2"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.2"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.13.2"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "1.21.9"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

# Dependencies for testing purposes only
[[constraint]]
  name = "github.com/onsi/gomega"
  version = "~1.3.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "~1.4.0"

[prune]
  unused-packages = true
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    non-go = false


[[constraint]]
  name = "github.com/golang/mock"
  version = "1.2.0"