alicloud:
  region: cn-beijing

create:
  vpc: true

clusterName: test-namespace

sshPublicKey: sshkey-12345

vpc:
  id: ${alicloud_vpc.vpc.id}
  cidr: 10.10.10.10/6
  natGatewayID: ${alicloud_nat_gateway.nat_gateway.id}
  snatTableID: ${alicloud_nat_gateway.nat_gateway.snat_table_ids}
  internetChargeType: PayByTraffic

zones:
- name: cn-beijing-a
  cidr:
    workers: 10.250.0.0/19
- name: cn-beijing-b
  cidr:
    workers: 10.250.32.0/19

names:
  configuration: shoot.tf-config
  variables: shoot.tf-vars
  state: shoot.tf-state

initializeEmptyState: true

outputKeys:
  securityGroupID: sg_id
  vpcID: vpc_id
  vpcCIDR: vpc_cidr
  keyPairName: key_pair_name
  vswitchNodesPrefix: vswitch_z
