apiVersion: apps/v1
kind: Deployment
metadata:
  name: gardener-extension-os-ubuntu
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-os-ubuntu
    helm.sh/chart: gardener-extension-os-ubuntu
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: gardener-extension-os-ubuntu
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gardener-extension-os-ubuntu
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: gardener-extension-os-ubuntu
      containers:
      - name: gardener-extension-os-ubuntu
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /gardener-extension-hyper
        - os-ubuntu-controller-manager
        - --max-concurrent-reconciles={{ .Values.concurrentSyncs }}
        env:
        - name: LEADER_ELECTION_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
