{{- range $index, $machineClass := .Values.machineClasses }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    gardener.cloud/purpose: machineclass
type: Opaque
data:
  userData: {{ $machineClass.secret.cloudConfig | b64enc }}
  vsphereHost: {{ $machineClass.secret.vsphereHost | b64enc }}
  vsphereUsername: {{ $machineClass.secret.vsphereUsername | b64enc }}
  vspherePassword: {{ $machineClass.secret.vspherePassword | b64enc }}
  vsphereInsecureSSL: {{ $machineClass.secret.vsphereInsecureSSL | b64enc }}
---
apiVersion: machine.sapcloud.io/v1alpha1
kind: MachineClass
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
providerSpec:
  region: {{ $machineClass.region }}
  datacenter: {{ $machineClass.datacenter }}
{{- if $machineClass.hostSystem }}
  hostSystem: {{ $machineClass.hostSystem }}
{{- else }}
{{- if $machineClass.resourcePool }}
  resourcePool: {{ $machineClass.resourcePool }}
{{- else }}
  computeCluster: {{ $machineClass.computeCluster }}
{{- end }}
{{- end }}
  network: {{ $machineClass.network }}
{{- if $machineClass.folder }}
  folder: {{ $machineClass.folder }}
{{- end }}
{{- if $machineClass.datastoreCluster }}
  datastoreCluster: {{ $machineClass.datastoreCluster }}
{{- else }}
  datastore: {{ $machineClass.datastore }}
{{- end }}
  templateVM: {{ $machineClass.templateVM }}
{{- if $machineClass.guestId }}
  guestId: {{ $machineClass.guestId }}
{{- end }}
  numCpus: {{ $machineClass.numCpus }}
  memory: {{ $machineClass.memory }}
  systemDisk:
  {{ toYaml $machineClass.systemDisk | indent 2 }}
  sshKeys:
{{ toYaml $machineClass.sshKeys | indent 4 }}
{{- if $machineClass.tags }}
  tags:
{{ toYaml $machineClass.tags | indent 4 }}
{{- end }}
secretRef:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
provider: vspheredriver//127.0.0.1:8080
{{- end }}
