---
apiVersion: alicloud.provider.extensions.config.gardener.cloud/v1alpha1
kind: ControllerConfiguration
clientConnection:
  acceptContentTypes: application/json
  contentType: application/json
  qps: 100
  burst: 130
machineImages:
- name: coreos-alicloud
  version: 2023.4.0
  regions:
  - imageID: coreos_2023_4_0_64_30G_alibase_20190319.vhd
    region: ap-southeast-1
- name: coreos
  version: 2191.4.1  
  regions:
  - imageID: m-t4n09r2ooaf9a9gzq18f
    region: ap-southeast-1
etcd:
  storage:
    className: gardener.cloud-fast
    capacity: 25Gi
  backup:
    schedule: "0 */24 * * *"
