machineClasses:
- name: class-1
# labels:
#   foo: bar
  projectID: abcd-1234-fff
  OS: alpine_3
  billingCycle: hourly
  facility:
  - ewr1
  description: An optional description for machines created by that class.
  machineType: t1.small
  sshKeys:
  - 12345-abcd567-aaf2
  secret:
    cloudConfig: abc
    apiToken: "abd5678"
  tags:
  - kubernetes.io/cluster/foo
  - kubernetes.io/role/node
