---
apiVersion: openstack.provider.extensions.config.gardener.cloud/v1alpha1
kind: ControllerConfiguration
clientConnection:
  acceptContentTypes: application/json
  contentType: application/json
  qps: 100
  burst: 130
machineImages:
- name: coreos
  version: 2023.5.0
  cloudProfiles:
  - name: eu-de-1
    image: coreos-2023.5.0
etcd:
  storage:
    className: gardener.cloud-fast
    capacity: 25Gi
  backup:
    schedule: "0 */24 * * *"
